// GALLERY PAGE ACTIONS
export const GET_KIMONOS_SUCCESS = 'GET_KIMONOS_SUCCESS';
export const GET_KIMONOS_FAILURE = 'GET_KIMONOS_FAILURE';
export const SAVE_FINISHED_IMAGE = 'SAVE_FINISHED_IMAGE';
export const USER_FINISHED_DESIGNING = 'USER_FINISHED_DESIGNING';
export const USER_UPLOADED_IMAGE = 'USER_UPLOADED_IMAGE';
export const USER_LEFT_DESIGN_PAGE = 'USER_LEFT_DESIGN_PAGE';